spring:
  application:
    name: mars-note

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  root
    password:  1347
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名
    map-underscore-to-camel-case: true
#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug